version: "3.8"
services:
  webapp:
    container_name: demo_web
    build:
      context: .
      dockerfile: .docker/webapp/Dockerfile
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./src:/srv/app
    restart: unless-stopped
    networks:
      - app-network
  database:
    image: mariadb:10.4
    container_name: demo_db
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - TZ=Asia/Bangkok
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge